# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HasegawaKishinoYano <- function(equilibrium, transition_rate = 1, transversion_rate = 1) {
    .Call('PalantiR_HasegawaKishinoYano', PACKAGE = 'PalantiR', equilibrium, transition_rate, transversion_rate)
}

MutationSelection <- function(population_size, mutation_rate, nucleotide_equilibrium, nucleotide_transition, fitness, scaling_type = "synonymous") {
    .Call('PalantiR_MutationSelection', PACKAGE = 'PalantiR', population_size, mutation_rate, nucleotide_equilibrium, nucleotide_transition, fitness, scaling_type)
}

CoEvolution <- function(population_size, mutation_rate, nucleotide_equilibrium, nucleotide_transition, fitness_1, fitness_2, delta, scaling_type = "synonymous") {
    .Call('PalantiR_CoEvolution', PACKAGE = 'PalantiR', population_size, mutation_rate, nucleotide_equilibrium, nucleotide_transition, fitness_1, fitness_2, delta, scaling_type)
}

Phylogeny <- function(newick_path) {
    .Call('PalantiR_Phylogeny', PACKAGE = 'PalantiR', newick_path)
}

equilibrium_to_fitness <- function(equilibrium, population_size) {
    .Call('PalantiR_equilibrium_to_fitness', PACKAGE = 'PalantiR', equilibrium, population_size)
}

simulate_over_phylogeny <- function(tree, substitution_model, sequence, rate = 1) {
    .Call('PalantiR_simulate_over_phylogeny', PACKAGE = 'PalantiR', tree, substitution_model, sequence, rate)
}

simulate_over_interval_phylogeny <- function(tree, mode_tree, substitution_models, sequence, start_mode, rate = 1, segment_length = 0.001, tolerance = 0.001) {
    .Call('PalantiR_simulate_over_interval_phylogeny', PACKAGE = 'PalantiR', tree, mode_tree, substitution_models, sequence, start_mode, rate, segment_length, tolerance)
}

simulate_with_nested_heterogeneity <- function(tree, switching_model, substitution_models, sequence, start_mode, rate = 1, switching_rate = 1, segment_length = 0.001, tolerance = 0.001) {
    .Call('PalantiR_simulate_with_nested_heterogeneity', PACKAGE = 'PalantiR', tree, switching_model, substitution_models, sequence, start_mode, rate, switching_rate, segment_length, tolerance)
}

compare_modes <- function(substitution_models, intervals) {
    .Call('PalantiR_compare_modes', PACKAGE = 'PalantiR', substitution_models, intervals)
}

Sequence <- function(sequence, type = "codon", mode = 0L) {
    .Call('PalantiR_Sequence', PACKAGE = 'PalantiR', sequence, type, mode)
}

as_compound <- function(sequence, mode) {
    .Call('PalantiR_as_compound', PACKAGE = 'PalantiR', sequence, mode)
}

sample_sequence <- function(model, length) {
    .Call('PalantiR_sample_sequence', PACKAGE = 'PalantiR', model, length)
}

as_amino_acid <- function(codons) {
    .Call('PalantiR_as_amino_acid', PACKAGE = 'PalantiR', codons)
}

