# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HasegawaKishinoYano <- function(equilibrium, transition_rate = 1, transversion_rate = 1) {
    .Call('PalantiR_HasegawaKishinoYano', PACKAGE = 'PalantiR', equilibrium, transition_rate, transversion_rate)
}

MutationSelection <- function(population_size, mutation_rate, nucleotide_equilibrium, nucleotide_transition, fitness, scaling_type = "synonymous") {
    .Call('PalantiR_MutationSelection', PACKAGE = 'PalantiR', population_size, mutation_rate, nucleotide_equilibrium, nucleotide_transition, fitness, scaling_type)
}

decorate_codon_substitutions <- function(substitutions) {
    .Call('PalantiR_decorate_codon_substitutions', PACKAGE = 'PalantiR', substitutions)
}

Phylogeny <- function(newick) {
    .Call('PalantiR_Phylogeny', PACKAGE = 'PalantiR', newick)
}

equilibrium_to_fitness <- function(equilibrium, population_size) {
    .Call('PalantiR_equilibrium_to_fitness', PACKAGE = 'PalantiR', equilibrium, population_size)
}

simulate_over_phylogeny <- function(tree, substitution_model, sequence, rate = 1) {
    .Call('PalantiR_simulate_over_phylogeny', PACKAGE = 'PalantiR', tree, substitution_model, sequence, rate)
}

